### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by fvitalini**
Minor fixes from reading the tech guides

### CODE REVIEW

**Comment by fvitalini** [comment]
Unsure why automated checks are failing (error message: "Error: pandoc document conversion failed with error 2"), anyhow this PR is only to point out minor typos.

**Comment by riccardoporreca** [comment]
> Unsure why automated checks are failing (error message: "Error: pandoc document conversion failed with error 2")

This is due to rstudio/bookdown#979 (the corresponding fix is not released to CRAN yet), which is causing a problem on Travis since it uses pandoc `2.2` as [default version](https://docs.travis-ci.com/user/languages/r/#pandoc) (as of Nov 2020). I recommend aligning the pandoc version on Travis to the newer version used e.g. by RStudio (2.7.3 as of Nov 2020).

**Review by riccardoporreca — APPROVED** [review]
LGTM

**Comment by Chargothrond** [comment]
The following title:

CI/CD pypelines for automatic deployment of a R Shiny web app

Should say pipelines instead of pypelines

**Comment by fvitalini** [comment]
links exist and are accessible but the checks keep failing

**Pull request merged**
