### PR TITLE
update packaged shiny apps

### PR DESCRIPTION
**Pull request by Chargothrond**
To consider moving the new information into the existing shiny-ci-cd chapter as "deploy packaged shiny app without golem".

The text itself is in a draft state and should be reviewed for its correctness / formulation.

### CODE REVIEW

**Review by fvitalini — CHANGES_REQUESTED** [review]
I have added this a a chapter and committed some rewording. @Chargothrond  check if you like it. 

Also, before merging, I think this cchapter needs a bit more structure. For now it looks more like internal notes. I think we should have a section about deployment with golem and an example of a minimal app without golem.

**Comment by Chargothrond** [comment]
Thanks for the improvements, I committed a few more refinements.

I didn't put any structure yet on purpose, as we might want to integrate this into the shiny-ci-cd.Rmd chapter rather than creating its own. However, I preferred so far to have a separate file to not need to resolve merge conflicts if meanwhile we have merged the other branches that affect shiny-ci-cd.Rmd.

I agree that it then makes sense to mention a bit more about the deployment in general on the first paragraphs, also referring to golem. If it's a standalone chapter, we will need more introduction / structure, which is part of the reason why I'd prefer to move it into shiny-ci-cd.Rmd.

**Comment by Chargothrond** [comment]
Aligned the bookdown yaml to master to prevent merge conflict and moved the shiny deploy section into the shiny ci / cd chapter, barely modified.

**Review by fvitalini — APPROVED** [review]

**Comment by fvitalini** [comment]
@Chargothrond I have fixed some issues that were making the automatic checks fail and have included a minor rewording to better introduce the new sub-chapter. see if you like it.

**Comment by Chargothrond** [comment]
@fvitalini The updates look good to me. However the setup chunk was copied over by mistake and I have removed it. I don't think we then need the updated r setup names (also not sure why you changed just one of the others), but it doesn't harm to have more explicit names anyway.

**Pull request merged**
